### ISSUE TITLE
Migration steps

### ISSUE THREAD

**Issue by rajzik** [Oriflame/lumos#3]
- [x] migrate packages to new namespace; Done by #2 
- [x] Update readme; Done by #2 
- [x] Clean changelogs; Done by #2
- [x] Reset versions; Done by #2
- [x] Setup policies
- [x] Remove tags
